name: mimic-iv-etl
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - pandas=2.2.1
  - pyspark=3.5.1
  - xgboost=2.0.3
  - scikit-learn=1.4.1.post1
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - jupyterlab=4.1.5
  - ipywidgets=8.1.2